apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-and-build-run-
spec:
  serviceAccountName: ctbc-deployer
  pipelineRef:
    name: clone-and-build
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi